packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  esbuild: true
  '@tailwindcss/oxide': true
  unrs-resolver: true
